# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messenger.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fmessenger.proto\"O\n\x07Message\x12\x0e\n\x06sender\x18\x01 \x01(\t\x12\x10\n\x08receiver\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\x12\x11\n\ttimestamp\x18\x04 \x01(\x03\"0\n\x04\x43hat\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x1a\n\x08messages\x18\x02 \x03(\x0b\x32\x08.Message\"%\n\x11\x43reateChatRequest\x12\x10\n\x08username\x18\x01 \x01(\t\"2\n\x0cLoginRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"1\n\rLoginResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"5\n\x0fRegisterRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"4\n\x10RegisterResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x94\x01\n\tUserState\x12\x10\n\x08password\x18\x01 \x01(\t\x12$\n\x05\x63hats\x18\x02 \x03(\x0b\x32\x15.UserState.ChatsEntry\x12\x1a\n\x08messages\x18\x03 \x03(\x0b\x32\x08.Message\x1a\x33\n\nChatsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x14\n\x05value\x18\x02 \x01(\x0b\x32\x05.Chat:\x02\x38\x01\x32\xd5\x01\n\tMessenger\x12!\n\x0bSendMessage\x12\x08.Message\x1a\x08.Message\x12#\n\x0eGetChatHistory\x12\x05.Chat\x1a\x08.Message0\x01\x12\'\n\nCreateChat\x12\x12.CreateChatRequest\x1a\x05.Chat\x12&\n\x05Login\x12\r.LoginRequest\x1a\x0e.LoginResponse\x12/\n\x08Register\x12\x10.RegisterRequest\x1a\x11.RegisterResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'messenger_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_USERSTATE_CHATSENTRY']._options = None
  _globals['_USERSTATE_CHATSENTRY']._serialized_options = b'8\001'
  _globals['_MESSAGE']._serialized_start=19
  _globals['_MESSAGE']._serialized_end=98
  _globals['_CHAT']._serialized_start=100
  _globals['_CHAT']._serialized_end=148
  _globals['_CREATECHATREQUEST']._serialized_start=150
  _globals['_CREATECHATREQUEST']._serialized_end=187
  _globals['_LOGINREQUEST']._serialized_start=189
  _globals['_LOGINREQUEST']._serialized_end=239
  _globals['_LOGINRESPONSE']._serialized_start=241
  _globals['_LOGINRESPONSE']._serialized_end=290
  _globals['_REGISTERREQUEST']._serialized_start=292
  _globals['_REGISTERREQUEST']._serialized_end=345
  _globals['_REGISTERRESPONSE']._serialized_start=347
  _globals['_REGISTERRESPONSE']._serialized_end=399
  _globals['_USERSTATE']._serialized_start=402
  _globals['_USERSTATE']._serialized_end=550
  _globals['_USERSTATE_CHATSENTRY']._serialized_start=499
  _globals['_USERSTATE_CHATSENTRY']._serialized_end=550
  _globals['_MESSENGER']._serialized_start=553
  _globals['_MESSENGER']._serialized_end=766
# @@protoc_insertion_point(module_scope)
